# Generated by Django 6.0.2 on 2026-03-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=200, verbose_name='Şikayet Konusu')),
                ('mesaj', models.TextField(verbose_name='Şikayet Detayı')),
                ('kategori', models.CharField(choices=[('yemekhane', 'Yemekhane'), ('temizlik', 'Temizlik / Hijyen'), ('derslik', 'Derslik / Lab'), ('idari', 'İdari İşler')], default='genel', max_length=50)),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('islemde', 'İşlemde'), ('cozuldu', 'Çözüldü')], default='beklemede', max_length=20)),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci Adı')),
            ],
        ),
    ]
